export const Header_Title_Evaluation = [
  ["EMPRESA", "FECHA DE EVALUACIÓN"],
  ["DIRECCIÓN", "EVALUACIÓN REALIZADA POR"],
  ["DEPARTAMENTO/LOCALIDAD", "AREA SUJETA A EVALUACIÓN"],
  ["EVALUACIÓN COORDINADA POR", "PUESTOS DE TRABAJO A EVALUAR"],
];

export const Header_Keys_Evaluation = [
  ["EMPRESA", "FECHA"],
  ["DIRECCION", "ELABORADOR"],
  ["DEPARTAMENTO", "AREAEVALUADA"],
  ["COORDINADOR", "PUESTOS"],
];
