export const x = [
  {
    AcreditacionMITRAB: "038-12-2022",
    Anio: "2024",
    Antecedentes:
      "Antecedentes \r\n\r\nTropigas\n de Nicaragua S.A, inicio operaciones en el año 1954, siendo una empresa líder\n en comercialización y distribución de gas licuado derivado del petróleo (GLP),\n abarcando la mayor parte del mercado y enfocado en la distribución y suministros\n de GLP al sector Industrial, Comercial y Domestico.\r\n\r\nSomos\nparte del grupo EDZA, un Holding regional que se constituye de varias compañías\ninternacionales especializadas en la distribución de gas, fabricación de\ncilindros y la industria de certificación de normas de calidad en el manejo de\nGLP. Producto indispensable en los hogares y empresa nicaragüense;\r\n\r\nServicios\r\n\r\nGas a Granel\r\n\r\nEs\nde uso doméstico, generalmente en el comercio o industria por medio de tanques\nestacionarios, el cual se abastece por una unidad de reparto. Valores\r\n\r\nGas a Carburación\r\n\r\nUtilizado\nen los vehículos después de realizarle la instalación del equipo requerido para\nel funcionamiento con este producto, y puede ser alternado con el sistema de\ncombustión que el vehículo trae de fábrica, es principalmente instalado en los\nvehículos que utilizan gasolina.\r\n\r\nGas en Cilindro\r\n\r\nUtilizado\nespecialmente por la mayoría de hogares, este es trasportado en recipientes\n(cilindros) más pequeños para su uso, el mismo es vendido por libra, y las\ncapacidades más comunes son los cilindros de 25, 35 y 100 libras, contamos\ntambién con presentaciones de 40 y 60 libras, y el llenado de cilindros de\notras capacidades en nuestras respectivas plantas.\r\n\r\nEn\neste sistema a GRANEL consiste en la instalación de tanques  fijos de distinto tamaños desde (50 hasta\n50,000 galones) en los lugares de consumo, siendo abastecido en el mismo sitio\npor un camión cisterna, mediante rutas establecidas de atención al cliente,\nComo combustible alternativo, el uso de GLP a Granel  se adapta a cada necesidad de acuerdo al\nasesoramiento especializado de nuestro personal altamente calificado, que\npermite a nuestro clientes optimizar con cada nivel de consumo el máximo uso,\nlogrando mayor rendimiento a un menor costo\r\n\r\n Nuestros clientes Hoteleros utilizan el\nservicio a Granel para producir energía en sus áreas de lavanderías, lo cual\nles reduce considerablemente el costo de energía eléctrica. De igual manera,\nlas panaderías emplean este sistema para encender sus hornos.\r\n\r\nSomos\nespecialista en instalación de:\r\nCalentadores\nde agua\r\nGeneradores\nEléctricos.\r\nCocinas\nDomesticas.Equipos\nindustriales que operan con gas",
    Cantidad_de_Areas: "2",
    Cantidad_de_AreasLetras: "dos",
    Cantidad_de_Riesgos: "9",
    Cantidad_de_RiesgosLetras: "nueve",
    CargoElaborador: "Consultor - Docente",
    Coordinador: "Ing. Alexander Baldelomar",
    Departamento: "Leon",
    Direccion: "el kilómetro 91 ½ Carretera León-Chinandega",
    Elaborador: "Ing. Marlon Vendaña Reyes",
    Empresa: "TROPIGAS PLANTEL LEON",
    FechaFin: "28 diciembre 2022",
    FechaFinLetras: "28 diciembre 2022",
    FechaInicio: "27 diciembre 2022",
    FilaMatriz: [
      {
        Area: "OFICINAS ADMINISTRATIVAS",
        FilaFactor: [
          {
            FactorRiesgo: "Entorno Físico",
            FilaRiesgo: [
              {
                Peligro: "Oscilaciones  en maquinas y equipos",
              },
              {
                Peligro: "Radiación solar, UV, etc",
              },
            ],
          },
          {
            FactorRiesgo: "Contaminantes",
            FilaRiesgo: [
              {
                Peligro: "Hongos, Bacterias y Virus",
              },
              {
                Peligro: "Material Particulado en suspensión",
              },
              {
                Peligro: "Quimicos vaporizados o en aerosol",
              },
            ],
          },
          {
            FactorRiesgo: "Condiciones de Seguridad",
            FilaRiesgo: [
              {
                Peligro: "Material Particulado en proyección",
              },
              {
                Peligro: "Montacargas, pallet jack",
              },
              {
                Peligro: "Superficies Calientes",
              },
            ],
          },
        ],
        FilaNivelFactor: {
          FilaNivelRiesgo: [
            {
              FilaNivelRiesgo: [
                {
                  NivelPeligro: "TRIVIAL",
                },
                {
                  NivelPeligro: "TOLERABLE",
                },
              ],
            },
            {
              FilaNivelRiesgo: [
                {
                  NivelPeligro: "MODERADO",
                },
                {
                  NivelPeligro: "IMPORTANTE",
                },
                {
                  NivelPeligro: "SEVERO",
                },
              ],
            },
            {
              FilaNivelRiesgo: [
                {
                  NivelPeligro: "TOLERABLE",
                },
                {
                  NivelPeligro: "TOLERABLE",
                },
                {
                  NivelPeligro: "TOLERABLE",
                },
              ],
            },
          ],
        },
        Puestos: "ADMINISTRADOR",
        TrabajadoresExpuestos: 1,
      },
      {
        Area: "BOMBA DE INCENDIO",
        FilaFactor: [
          {
            FactorRiesgo: "Entorno Físico",
            FilaRiesgo: [
              {
                Peligro: "Radiación solar, UV, etc",
              },
            ],
          },
          {
            FactorRiesgo: "Contaminantes",
            FilaRiesgo: [
              {
                Peligro: "Hongos, Bacterias y Virus",
              },
            ],
          },
          {
            FactorRiesgo: "Condiciones de Seguridad",
            FilaRiesgo: [
              {
                Peligro: "Montacargas, pallet jack",
              },
              {
                Peligro: "Vehiculos, Camiones, Acoplados",
              },
            ],
          },
        ],
        FilaNivelFactor: {
          FilaNivelRiesgo: [
            {
              FilaNivelRiesgo: [
                {
                  NivelPeligro: "TOLERABLE",
                },
              ],
            },
            {
              FilaNivelRiesgo: [
                {
                  NivelPeligro: "TRIVIAL",
                },
              ],
            },
            {
              FilaNivelRiesgo: [
                {
                  NivelPeligro: "MODERADO",
                },
                {
                  NivelPeligro: "TOLERABLE",
                },
              ],
            },
          ],
        },
        Puestos: "BOMBA DE INCENDIO",
        TrabajadoresExpuestos: 2,
      },
    ],
    FilaProbabilidad: [
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "10.00%",
        ProbabilidadMedia: "0.00%",
        Riesgo: "Vibraciones",
      },
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "0.00%",
        ProbabilidadMedia: "45.00%",
        Riesgo: "Radiaciones No Ionizantes",
      },
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "10.00%",
        ProbabilidadMedia: "25.00%",
        Riesgo: "Contaminantes Biológicos",
      },
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "0.00%",
        ProbabilidadMedia: "15.00%",
        Riesgo: "Contaminantes Químicos (Polvo)",
      },
      {
        ProbabilidadAlta: "35.00%",
        ProbabilidadBaja: "0.00%",
        ProbabilidadMedia: "0.00%",
        Riesgo: "Contaminantes Químicos (Neblina)",
      },
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "0.00%",
        ProbabilidadMedia: "30.00%",
        Riesgo: "Proyección de Partículas",
      },
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "10.00%",
        ProbabilidadMedia: "30.00%",
        Riesgo: "Manipulación de Transporte",
      },
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "0.00%",
        ProbabilidadMedia: "30.00%",
        Riesgo: "Contacto con superficies Calientes",
      },
      {
        ProbabilidadAlta: "0.00%",
        ProbabilidadBaja: "0.00%",
        ProbabilidadMedia: "15.00%",
        Riesgo: "Accidente vehicular",
      },
    ],
    Fila_Areas: [
      {
        AREA: "OFICINAS ADMINISTRATIVAS",
        PUESTOS: "ADMINISTRADOR",
      },
      {
        AREA: "BOMBA DE INCENDIO",
        PUESTOS: "BOMBA DE INCENDIO",
      },
    ],
    Fila_AreasPeligros: [
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.200000000000000",
      },
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.600000000000000",
      },
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.500000000000000",
      },
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.300000000000000",
      },
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.700000000000000",
      },
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.600000000000000",
      },
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.600000000000000",
      },
      {
        AreaP: "OFICINAS ADMINISTRATIVAS",
        PROBABILIDAD: "0.600000000000000",
      },
      {
        AreaP: "BOMBA DE INCENDIO",
        PROBABILIDAD: "0.300000000000000",
      },
      {
        AreaP: "BOMBA DE INCENDIO",
        PROBABILIDAD: "0.200000000000000",
      },
      {
        AreaP: "BOMBA DE INCENDIO",
        PROBABILIDAD: "0.200000000000000",
      },
      {
        AreaP: "BOMBA DE INCENDIO",
        PROBABILIDAD: "0.300000000000000",
      },
    ],
    Fila_kcal: [
      {
        TipoTrabajo: "MUY PESADO",
        kcal: 1980,
        kcal1Brazo: "0.7",
        kcal2Brazo: "0",
        kcalAndando: "0",
        kcalArea: "OFICINAS ADMINISTRATIVAS",
        kcalDepie: "0",
        kcalMetBasal: "0",
        kcalPuesto: "ADMINISTRADOR",
        kcalSentado: " ",
        kcalSubPend: "0",
        kcalTodoCuerpo: "2.6",
        kcalTrabMan: "0",
      },
      {
        TipoTrabajo: "LEVE",
        kcal: 120,
        kcal1Brazo: "0",
        kcal2Brazo: "0",
        kcalAndando: "2",
        kcalArea: "BOMBA DE INCENDIO",
        kcalDepie: "0",
        kcalMetBasal: "0",
        kcalPuesto: "BOMBA DE INCENDIO",
        kcalSentado: "0",
        kcalSubPend: "0",
        kcalTodoCuerpo: " ",
        kcalTrabMan: "0",
      },
    ],
    LicenciaHYS: "904-10-2021",
    Logo: "Insertar Logo",
    Mision:
      "Nuestra Misión\r\n\r\nLograr\nla excelencia en atención, servicio y cobertura en el mercado nicaragüense con\nmayor valor en término de calidad. Confiabilidad, seguridad e innovación.\nConsolidando el liderazgo conforme la satisfacción total de nuestros clientes,\nmanteniendo siempre el estricto cumplimiento de las normativas nacionales e\ninternacionales.",
    Municipio: "León",
    PartTrivialTolerable: "68,75",
    ProbabilidadIncendio: "0,00 %",
    PuestoConMayorRiesgoModerado: "ADMINISTRADOR",
    PuestoCoordinador: "Administrador",
    REPETICION_POR_AREA: [
      {
        AREA: "OFICINAS ADMINISTRATIVAS",
        AREAEV: "OFICINAS ADMINISTRATIVAS",
        AREAEVALUADA: "OFICINAS ADMINISTRATIVAS",
        COORDINADOR: "Ing. Alexander Baldelomar",
        DEPARTAMENTO: "Leon",
        DIRECCION: "el kilómetro 91 ½ Carretera León-Chinandega",
        ELABORADOR: "Ing. Marlon Vendaña Reyes",
        EMPRESA: "TROPIGAS PLANTEL LEON",
        FECHA: "28 diciembre 2022",
        FILA_PROBABILIDAD: [
          {
            PORCENTAJE: "0.200000000000000",
            PROBABILIDAD: "(Probabilidad BAJA)",
            RIESGO: "Vibraciones",
          },
          {
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Radiaciones No Ionizantes",
          },
          {
            PORCENTAJE: "0.500000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Contaminantes Biológicos",
          },
          {
            PORCENTAJE: "0.300000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Contaminantes Químicos (Polvo)",
          },
          {
            PORCENTAJE: "0.700000000000000",
            PROBABILIDAD: "(Probabilidad ALTA)",
            RIESGO: "Contaminantes Químicos (Neblina)",
          },
          {
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Proyección de Partículas",
          },
          {
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Manipulación de Transporte",
          },
          {
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Contacto con superficies Calientes",
          },
        ],
        FILA_RIESGO_AREA: [
          {
            A: "0",
            ALTA: "",
            B: "1",
            BAJA: "X",
            C: "1",
            D: "1",
            E: "1",
            F: "1",
            FACTOR: "Entorno Físico",
            G: "1",
            H: "1",
            I: "0",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "2-20 Hz",
            PELIGRO: "Oscilaciones  en maquinas y equipos",
            PORCENTAJE: "0.200000000000000",
            PROBABILIDAD: "BAJA",
            RIESGO: "Vibraciones",
            SEVERO: "",
            TOLERABLE: "",
            TRIVIAL: "X",
          },
          {
            A: "0",
            ALTA: "",
            B: "0",
            BAJA: "X",
            C: "0",
            D: "1",
            E: "0",
            F: "1",
            FACTOR: "Entorno Físico",
            G: "1",
            H: "1",
            I: "1",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "Radiación electromagnética",
            PELIGRO: "Radiación solar, UV, etc",
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Radiaciones No Ionizantes",
            SEVERO: "",
            TOLERABLE: "X",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "",
            B: "0",
            BAJA: "",
            C: "0",
            D: "0",
            E: "0",
            F: "0",
            FACTOR: "Contaminantes",
            G: "0",
            H: "0",
            I: "0",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "X",
            MODERADO: "X",
            PARAMETRO: "Procedimiento de Trabajo",
            PELIGRO: "Hongos, Bacterias y Virus",
            PORCENTAJE: "0.500000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Contaminantes Biológicos",
            SEVERO: "",
            TOLERABLE: "",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "X",
            B: "1",
            BAJA: "",
            C: "0",
            D: "1",
            E: "1",
            F: "0",
            FACTOR: "Contaminantes",
            G: "0",
            H: "0",
            I: "1",
            IMPORTANTE: "X",
            J: "1",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "T.L.V. (A.C.G.I.H.)",
            PELIGRO: "Material Particulado en suspensión",
            PORCENTAJE: "0.300000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Contaminantes Químicos (Polvo)",
            SEVERO: "",
            TOLERABLE: "",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "X",
            B: "0",
            BAJA: "",
            C: "0",
            D: "0",
            E: "1",
            F: "0",
            FACTOR: "Contaminantes",
            G: "1",
            H: "1",
            I: "1",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "T.L.V. (A.C.G.I.H.)",
            PELIGRO: "Quimicos vaporizados o en aerosol",
            PORCENTAJE: "0.700000000000000",
            PROBABILIDAD: "ALTA",
            RIESGO: "Contaminantes Químicos (Neblina)",
            SEVERO: "X",
            TOLERABLE: "",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "",
            B: "0",
            BAJA: "X",
            C: "0",
            D: "0",
            E: "0",
            F: "0",
            FACTOR: "Condiciones de Seguridad",
            G: "0",
            H: "0",
            I: "0",
            IMPORTANTE: "",
            J: "0",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "Procedimiento de Trabajo",
            PELIGRO: "Material Particulado en proyección",
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Proyección de Partículas",
            SEVERO: "",
            TOLERABLE: "X",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "",
            B: "0",
            BAJA: "X",
            C: "0",
            D: "0",
            E: "0",
            F: "0",
            FACTOR: "Condiciones de Seguridad",
            G: "0",
            H: "0",
            I: "0",
            IMPORTANTE: "",
            J: "0",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "Procedimiento de Trabajo",
            PELIGRO: "Montacargas, pallet jack",
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Manipulación de Transporte",
            SEVERO: "",
            TOLERABLE: "X",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "",
            B: "0",
            BAJA: "X",
            C: "0",
            D: "0",
            E: "0",
            F: "0",
            FACTOR: "Condiciones de Seguridad",
            G: "0",
            H: "0",
            I: "0",
            IMPORTANTE: "",
            J: "0",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "Procedimiento de Trabajo",
            PELIGRO: "Superficies Calientes",
            PORCENTAJE: "0.600000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Contacto con superficies Calientes",
            SEVERO: "",
            TOLERABLE: "X",
            TRIVIAL: "",
          },
        ],
        IMPORTANTES: "12.50%",
        MODERADOS: "12.50%",
        PUESTOS: "ADMINISTRADOR",
        RIESGOLETRA: "ocho",
        RIESGONUM: "8",
        SEVEROS: "12.50%",
        TOLERABLES: "50.00%",
        TRIVIALES: "12.50%",
      },
      {
        AREA: "BOMBA DE INCENDIO",
        AREAEV: "BOMBA DE INCENDIO",
        AREAEVALUADA: "BOMBA DE INCENDIO",
        COORDINADOR: "Ing. Alexander Baldelomar",
        DEPARTAMENTO: "Leon",
        DIRECCION: "el kilómetro 91 ½ Carretera León-Chinandega",
        ELABORADOR: "Ing. Marlon Vendaña Reyes",
        EMPRESA: "TROPIGAS PLANTEL LEON",
        FECHA: "28 diciembre 2022",
        FILA_PROBABILIDAD: [
          {
            PORCENTAJE: "0.300000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Radiaciones No Ionizantes",
          },
          {
            PORCENTAJE: "0.200000000000000",
            PROBABILIDAD: "(Probabilidad BAJA)",
            RIESGO: "Contaminantes Biológicos",
          },
          {
            PORCENTAJE: "0.200000000000000",
            PROBABILIDAD: "(Probabilidad BAJA)",
            RIESGO: "Manipulación de Transporte",
          },
          {
            PORCENTAJE: "0.300000000000000",
            PROBABILIDAD: "(Probabilidad MEDIA)",
            RIESGO: "Accidente vehicular",
          },
        ],
        FILA_RIESGO_AREA: [
          {
            A: "0",
            ALTA: "",
            B: "0",
            BAJA: "X",
            C: "1",
            D: "1",
            E: "1",
            F: "1",
            FACTOR: "Entorno Físico",
            G: "1",
            H: "1",
            I: "0",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "Radiación electromagnética",
            PELIGRO: "Radiación solar, UV, etc",
            PORCENTAJE: "0.300000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Radiaciones No Ionizantes",
            SEVERO: "",
            TOLERABLE: "X",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "",
            B: "1",
            BAJA: "X",
            C: "1",
            D: "0",
            E: "1",
            F: "1",
            FACTOR: "Contaminantes",
            G: "1",
            H: "0",
            I: "0",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "Procedimiento de Trabajo",
            PELIGRO: "Hongos, Bacterias y Virus",
            PORCENTAJE: "0.200000000000000",
            PROBABILIDAD: "BAJA",
            RIESGO: "Contaminantes Biológicos",
            SEVERO: "",
            TOLERABLE: "",
            TRIVIAL: "X",
          },
          {
            A: "0",
            ALTA: "X",
            B: "1",
            BAJA: "",
            C: "1",
            D: "1",
            E: "1",
            F: "0",
            FACTOR: "Condiciones de Seguridad",
            G: "0",
            H: "1",
            I: "0",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "",
            MODERADO: "X",
            PARAMETRO: "Procedimiento de Trabajo",
            PELIGRO: "Montacargas, pallet jack",
            PORCENTAJE: "0.200000000000000",
            PROBABILIDAD: "BAJA",
            RIESGO: "Manipulación de Transporte",
            SEVERO: "",
            TOLERABLE: "",
            TRIVIAL: "",
          },
          {
            A: "0",
            ALTA: "",
            B: "1",
            BAJA: "X",
            C: "1",
            D: "0",
            E: "1",
            F: "0",
            FACTOR: "Condiciones de Seguridad",
            G: "1",
            H: "0",
            I: "0",
            IMPORTANTE: "",
            J: "1",
            MEDIA: "",
            MODERADO: "",
            PARAMETRO: "Procedimiento de Trabajo",
            PELIGRO: "Vehiculos, Camiones, Acoplados",
            PORCENTAJE: "0.300000000000000",
            PROBABILIDAD: "MEDIA",
            RIESGO: "Accidente vehicular",
            SEVERO: "",
            TOLERABLE: "X",
            TRIVIAL: "",
          },
        ],
        IMPORTANTES: "0.00%",
        MODERADOS: "25.00%",
        PUESTOS: "BOMBA DE INCENDIO",
        RIESGOLETRA: "cuatro",
        RIESGONUM: "4",
        SEVEROS: "0.00%",
        TOLERABLES: "50.00%",
        TRIVIALES: "25.00%",
      },
    ],
    Tecnico01: "Ing. Kevin Alvarado",
    Tecnico02: "Br. Henry Lacayo",
    TotalImportante: "6,25",
    TotalModerado: "18,75",
    TotalSevero: "6,25",
    TotalTolerable: "50,00",
    TotalTrivial: "18,75",
    Vision:
      "Nuestra Visión\r\n\r\nSer\nreconocido como empresa líder en el almacenamiento, envasado y distribución de\n(GLP), calificada como tal por nuestros clientes, empleados, comunidades y\naccionistas. Promoviendo la implementación de alternativas energéticas, en\nfunción de la conservación del medio ambiente.\r\n\r\nNuestra Valores\r\n\r\nSeguridad,\nIntegridad, Dinamismo, Excelencia en el Servicio",
  },
];
